force-app/main/default/objects/atl_KnowledgeArticle__c/atl_KnowledgeArticle__c.object-meta.xml
<CustomObject>
    <label>Knowledge Article</label>
    <nameField>
        <displayFormat>KA-{0000}</displayFormat>
        <label>Knowledge Article Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Knowledge Articles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/atl_KnowledgeArticle__c/fields/atl_Author__c.field-meta.xml
<CustomField>
    <fullName>atl_Author__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Who wrote the article</description>
    <label>Author</label>
    <referenceTo>User</referenceTo>
    <relationshipName>atl_KnowledgeArticles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/atl_KnowledgeArticle__c/fields/atl_AuthorName__c.field-meta.xml
<CustomField>
    <fullName>atl_AuthorName__c</fullName>
    <formula>atl_Author__r.FirstName &amp; &apos; &apos; &amp; atl_Author__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Author</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/atl_KnowledgeArticle__c/fields/atl_Body__c.field-meta.xml
<CustomField>
    <fullName>atl_Body__c</fullName>
    <description>Rich text area to hold the entire content of the article</description>
    <label>Body</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/atl_KnowledgeArticle__c/fields/atl_Domain__c.field-meta.xml
<CustomField>
    <fullName>atl_Domain__c</fullName>
    <label>Domain (Salesforce Only)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CPQ</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Platforms</fullName>
            </value>
            <value>
                <fullName>Integrations</fullName>
            </value>
            <value>
                <fullName>Platform</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/atl_KnowledgeArticle__c/fields/atl_Legacy__c.field-meta.xml
<CustomField>
    <fullName>atl_Legacy__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Denotes a legacy article</description>
    <label>Legacy</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/atl_KnowledgeArticle__c/fields/atl_Published__c.field-meta.xml
<CustomField>
    <fullName>atl_Published__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Drives whether articles are published or not</description>
    <label>Published</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/atl_KnowledgeArticle__c/fields/atl_SalesforceFileID__c.field-meta.xml
<CustomField>
    <fullName>atl_SalesforceFileID__c</fullName>
    <label>Salesforce File ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/atl_KnowledgeArticle__c/fields/atl_Sequence__c.field-meta.xml
<CustomField>
    <fullName>atl_Sequence__c</fullName>
    <label>Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/atl_KnowledgeArticle__c/fields/atl_Technology__c.field-meta.xml
<CustomField>
    <fullName>atl_Technology__c</fullName>
    <description>Technology that the knowledge article is tied to</description>
    <label>Technology</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Xactly</fullName>
            </value>
            <value>
                <fullName>DocuSign</fullName>
            </value>
            <value>
                <fullName>Gotransverse</fullName>
            </value>
            <value>
                <fullName>Conga</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/atl_KnowledgeArticle__c/fields/atl_Title__c.field-meta.xml
<CustomField>
    <fullName>atl_Title__c</fullName>
    <description>Title of the user-submitted article</description>
    <externalId>true</externalId>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/atl_KnowledgeBaseApexController.cls
public class atl_KnowledgeBaseApexController {
    
    @AuraEnabled
    // Initial resource query + record type retrieval
    public static List<atl_KnowledgeArticle__c> getKnowledgeArticles() {
        // Get all KAs
        List<atl_KnowledgeArticle__c> KAs = [SELECT Name, atl_Author__c, atl_Body__c, atl_Legacy__c, atl_AuthorName__c,
                                             atl_Published__c, atl_SalesforceFileID__c, atl_Title__c, atl_Domain__c, atl_Technology__c, atl_Sequence__c
                                             FROM atl_KnowledgeArticle__c ORDER BY atl_Sequence__c ASC];
        return KAs;    
    }
    
    @AuraEnabled
    // This grabs the values for the technology picklist
    public static List<String> getTechValues() {
        List<String> techs = new List<String>();
        for (Schema.PicklistEntry tech :atl_KnowledgeArticle__c.atl_Technology__c.getDescribe().getPicklistValues()) {
            techs.add(tech.getValue());
        }
        return techs;
    }
    
    @AuraEnabled
    // This grabs the values for the Domain picklist
    public static List<String> getDomainValues() {
        List<String> domains = new List<String>();
        for (Schema.PicklistEntry domain :atl_KnowledgeArticle__c.atl_Domain__c.getDescribe().getPicklistValues()) {
            domains.add(domain.getValue());
        }
        return domains;
    }
    
    @AuraEnabled
    // This grabs the specifics for the selected Knowledge Article
    public static atl_KnowledgeArticle__c getKnowledgeArticleDetails(Id recordId) {
        atl_KnowledgeArticle__c KA = [SELECT Name, atl_Author__c, atl_Body__c, atl_Legacy__c, atl_AuthorName__c,
                                      atl_Published__c, atl_SalesforceFileID__c, atl_Title__c, atl_Domain__c, atl_Technology__c, atl_Sequence__c
                                      FROM atl_KnowledgeArticle__c WHERE Id =:recordId ];
        return KA;
    }
}