force-app/main/default/objects/Emission_Factor__c/Emission_Factor__c.object-meta.xml
<CustomObject>
    <description>HT: Created for NZC Implementation UC003_US01, created to store different type of emission factors.</description>
    <label>Emission Factor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Emission Factors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Emission_Factor__c/fields/CFC_R22_Refrigerant_Emissions_Factor__c.field-meta.xml
<CustomField>
    <fullName>CFC_R22_Refrigerant_Emissions_Factor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CFC-R22 Refrigerant Emissions Factor</label>
    <referenceTo>RefrigerantEmssnFctr</referenceTo>
    <relationshipName>Load_Emission_Factors1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Emission_Factor__c/fields/HFC_125_Refrigerant_Emissions_Factor__c.field-meta.xml
<CustomField>
    <fullName>HFC_125_Refrigerant_Emissions_Factor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HFC-125 Refrigerant Emissions Factor</label>
    <referenceTo>RefrigerantEmssnFctr</referenceTo>
    <relationshipLabel>Emission Factors (HFC - 125 Refrigerant Emissions Factor)</relationshipLabel>
    <relationshipName>Load_Emission_Factors5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Emission_Factor__c/fields/HFC_134a_Refrigerant_Emissions_Factor__c.field-meta.xml
<CustomField>
    <fullName>HFC_134a_Refrigerant_Emissions_Factor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HFC-134a Refrigerant Emissions Factor</label>
    <referenceTo>RefrigerantEmssnFctr</referenceTo>
    <relationshipLabel>Emission Factors (HFC - 134a Refrigerant Emissions Factor)</relationshipLabel>
    <relationshipName>Load_Emission_Factors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Emission_Factor__c/fields/HFC_R32_Refrigerant_Emissions_Factor__c.field-meta.xml
<CustomField>
    <fullName>HFC_R32_Refrigerant_Emissions_Factor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HFC-R32 Refrigerant Emissions Factor</label>
    <referenceTo>RefrigerantEmssnFctr</referenceTo>
    <relationshipName>Load_Emission_Factors4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Emission_Factor__c/fields/HFC_R407c_Refrigerant_Emissions_Factor__c.field-meta.xml
<CustomField>
    <fullName>HFC_R407c_Refrigerant_Emissions_Factor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HFC-R407c Refrigerant Emissions Factor</label>
    <referenceTo>RefrigerantEmssnFctr</referenceTo>
    <relationshipName>Load_Emission_Factors3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Emission_Factor__c/fields/HFC_R410a_Refrigerant_Emissions_Factor__c.field-meta.xml
<CustomField>
    <fullName>HFC_R410a_Refrigerant_Emissions_Factor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HFC-R410a Refrigerant Emissions Factor</label>
    <referenceTo>RefrigerantEmssnFctr</referenceTo>
    <relationshipName>Load_Emission_Factors2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Emission_Factor__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Pending for approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Revised</fullName>
            </value>
            <value>
                <fullName>Pending with Level 2 Approver</fullName>
                <isActive>false</isActive>
                <label>Pending with Level 2 Approver</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Energy_Use_Data_Log__c/Energy_Use_Data_Log__c.object-meta.xml
<CustomObject>
    <description>HT: Created for NZC Implementation UC003_US05, created to store the energy use data logs.</description>
    <label>Energy Use Data Log</label>
    <nameField>
        <displayFormat>Log-{00000}</displayFormat>
        <label>Energy Use Data Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Energy Use Data Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Energy_Use_Data_Log__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>SB: Created for NZC Implementation
Purpose: for multi approver change request this field has been created to populate country from its parent site information record</description>
    <formula>TEXT(Site_Information__r.Country)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Energy_Use_Data_Log__c/fields/Fuel_Type__c.field-meta.xml
<CustomField>
    <fullName>Fuel_Type__c</fullName>
    <label>Fuel Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Energy_Use_Data_Log__c/fields/Site_Information__c.field-meta.xml
<CustomField>
    <fullName>Site_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Information</label>
    <referenceTo>StnryAssetEnvrSrc</referenceTo>
    <relationshipLabel>Energy_Use_Data_Logs</relationshipLabel>
    <relationshipName>Energy_Use_Data_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Energy_Use_Data_Log__c/fields/Stationary_Asset_Energy_Use__c.field-meta.xml
<CustomField>
    <fullName>Stationary_Asset_Energy_Use__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stationary Asset Energy Use</label>
    <referenceTo>StnryAssetEnrgyUse</referenceTo>
    <relationshipLabel>Energy_Use_Data_Logs</relationshipLabel>
    <relationshipName>Energy_Use_Data_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Energy_Use_Data_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>SB: Created for NZC Implementation
Purpose: Created to capture the Approval Status of the Record</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Pending Data Validator Approval</fullName>
            </value>
            <value>
                <fullName>Pending Data Approver Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Re-opened</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Energy_Use_Fuel_Type__mdt/Energy_Use_Fuel_Type__mdt.object-meta.xml
<CustomObject>
    <description>HT: Created for NZC Implementation, UC003_US02, UC003_US12, UC003_US15, created to store the fuel types which are visible on the Energy Use creation form for Data Processors.</description>
    <label>Energy Use Fuel Type</label>
    <pluralLabel>Energy Use Fuel Types</pluralLabel>
</CustomObject>

force-app/main/default/objects/Energy_Use_Fuel_Type__mdt/fields/Applicability_Picklist_Label__c.field-meta.xml
<CustomField>
    <fullName>Applicability_Picklist_Label__c</fullName>
    <label>Applicability Picklist Label</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Energy_Use_Fuel_Type__mdt/fields/Applicability_Values__c.field-meta.xml
<CustomField>
    <fullName>Applicability_Values__c</fullName>
    <label>Applicability Values</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Energy_Use_Fuel_Type__mdt/fields/Fuel_Type__c.field-meta.xml
<CustomField>
    <fullName>Fuel_Type__c</fullName>
    <label>Fuel Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Energy_Use_Fuel_Type__mdt/fields/isSectionOpen__c.field-meta.xml
<CustomField>
    <fullName>isSectionOpen__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isSectionOpen</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Energy_Use_Fuel_Type__mdt/fields/Refrigerant_Emissions_Factor__c.field-meta.xml
<CustomField>
    <fullName>Refrigerant_Emissions_Factor__c</fullName>
    <label>Refrigerant Emissions Factor</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Energy_Use_Fuel_Type__mdt/fields/Renewable_Energy_Type__c.field-meta.xml
<CustomField>
    <fullName>Renewable_Energy_Type__c</fullName>
    <label>Renewable Energy Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Energy_Use_Fuel_Type__mdt/fields/Scope_Number__c.field-meta.xml
<CustomField>
    <fullName>Scope_Number__c</fullName>
    <label>Scope Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Energy_Use_Fuel_Type__mdt/fields/Show_for_ULA__c.field-meta.xml
<CustomField>
    <fullName>Show_for_ULA__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Harshvardhan: Created this checkbox field for the ULA requirement. If this field is true, then the corresponding metadata record(Fuel Type) will be shown on the Data Entry form as part of ULA.</description>
    <label>Show for ULA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Energy_Use_Fuel_Type__mdt/fields/Show_Not_Applicable_For_Renewable__c.field-meta.xml
<CustomField>
    <fullName>Show_Not_Applicable_For_Renewable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Not Applicable For Renewable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Energy_Use_Fuel_Type__mdt/fields/UOM_Options__c.field-meta.xml
<CustomField>
    <fullName>UOM_Options__c</fullName>
    <label>UOM Options</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StnryAssetEnrgyUse/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>HA: Created for NZC Implementation, purpose: for multi approver change request this field has been created to populate country from from its parent site information record</description>
    <formula>TEXT(StnryAssetEnvrSrc.Country)</formula>
    <label>Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StnryAssetEnrgyUse/fields/I_have_reviewed_all_fields_and_data__c.field-meta.xml
<CustomField>
    <fullName>I_have_reviewed_all_fields_and_data__c</fullName>
    <defaultValue>false</defaultValue>
    <description>HA: Created for NZC Implementation, UC003_US04 Purpose: This field is to check by the user when they have created or edited any data, declaring that they have filled all the data and data has been checked before saving.</description>
    <label>I confirm the above</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StnryAssetEnrgyUse/fields/Procurement_Emissions_Factor_Set__c.field-meta.xml
<CustomField>
    <fullName>Procurement_Emissions_Factor_Set__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>AJ: Created for NZC Implementation, This field is created to capture Procurement Emission Factor Set:</description>
    <label>Procurement Emissions Factor Set WTT</label>
    <referenceTo>PcmtEmssnFctrSet</referenceTo>
    <relationshipLabel>Stationary Asset Energy Use</relationshipLabel>
    <relationshipName>Stationary_Asset_Energy_Use</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StnryAssetEnrgyUse/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>VB, Venkat: Created for NZC Implementation UC004_US04,
Purpose: Created to capture the Approval Status of the Record</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Pending Data Validator Approval</fullName>
            </value>
            <value>
                <fullName>Pending Data Approver Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Re-opened</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/StnryAssetEnvrSrc/fields/I_have_reviewed_all_fields_and_data__c.field-meta.xml
<CustomField>
    <fullName>I_have_reviewed_all_fields_and_data__c</fullName>
    <defaultValue>false</defaultValue>
    <description>HA: Created for NZC Implementation, UC001_US07. Purpose: This field is to check by the user when they have created or edited any data, declaring that they have filled all the data and data has been checked before saving.</description>
    <label>I confirm the above</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StnryAssetEnvrSrc/fields/NZC_ULA__c.field-meta.xml
<CustomField>
    <fullName>NZC_ULA__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Harshvardhan: Created this checkbox field for the ULA requirement. If this field is true, then the site information is ULA.</description>
    <label>ULA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StnryAssetEnvrSrc/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>VB, Venkat: Created for NZC Implementation UC002_US01
Purpose: To Capture the Approval Status of the record.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Pending for Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Revised</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EnergyUseControllerUpdated.cls
/******************************************************************************
Class Name: EnergyUseControllerUpdated
Created By : Harshvardhan Tiwari
Created : 11-Oct-23
Description : Created to get the metadata records to arrange them and show them on the data entry form, 
send the energy use record for approval, link the uploaded file to the record and to link the refrigerant record with
its emission factor.
==============================
Change Log:
==============================
Changed By: Harshvardhan Tiwari
Date: 15-July-2024
Description: 
1. Added createEnergyUseRecord method to take inputs from LWC component and create new Energy Use Records. 
2. Created EnergyUseWrapperFromJS wrapper class to capture information in from LWC
*************************************************************************/
public with sharing class EnergyUseControllerUpdated {
    
    //get the custom metadata records to pass it into lwc and show it as a form
    @AuraEnabled(cacheable=true)
    public static EnergyUseControllerUpdated.EnergyUseMetadataWrapper getMetadataInformation(String parentSiteInfo){
        //public static List<EnergyUseControllerUpdated.ScopeMetadataWrapper> getMetadataInformation(String parentSiteInfo){
        if(String.isBlank(parentSiteInfo)) return null;
        EnergyUseMetadataWrapper tempMetadataWrapper = new EnergyUseMetadataWrapper();
        StnryAssetEnvrSrc siteInfo = [SELECT Id, NZC_ULA__c, Name, Country, State FROM StnryAssetEnvrSrc WHERE Id=:parentSiteInfo LIMIT 1];
        if(siteInfo == null){
            return null;
        } 
        //refrigerant emission factor logic starts
        Map<String,String> refEmissionMap = getRefEmissionFactor(siteInfo);
        //refrigerant emission factor logic ends
        
        if(refEmissionMap == null || refEmissionMap.keySet().isEmpty()){
            tempMetadataWrapper.approvedEmissionFactorsFound = false;
            tempMetadataWrapper.scopeMetadataWrapperData = null;
            return tempMetadataWrapper;
        }
        
        List<Energy_Use_Fuel_Type__mdt> fuelTypeMetaList = new List<Energy_Use_Fuel_Type__mdt>();
        
        fuelTypeMetaList = [SELECT Fuel_Type__c,
                            MasterLabel,
                            Applicability_Picklist_Label__c,
                            Applicability_Values__c,
                            Show_Not_Applicable_For_Renewable__c,
                            UOM_Options__c,
                            Scope_Number__c,
                            Refrigerant_Emissions_Factor__c,
                            isSectionOpen__c,
                            Renewable_Energy_Type__c,
                            Order__c ,
                            Show_for_ULA__c                                            
                            FROM Energy_Use_Fuel_Type__mdt
                            WHERE Show_for_ULA__c = :siteInfo.NZC_ULA__c
                            ORDER BY Order__c ASC];
        
        List<EnergyUseControllerUpdated.ScopeMetadataWrapper> resultList = new List<ScopeMetadataWrapper>();
        Set<String> scopeList = new Set<String>();
        for(Energy_Use_Fuel_Type__mdt eft : fuelTypeMetaList){
            scopeList.add(eft.Scope_Number__c);
        }
        for(String scopeVar:scopeList){
            ScopeMetadataWrapper scopeWrapperVar = new ScopeMetadataWrapper();
            scopeWrapperVar.scopeLabel = scopeVar;
            List<Map<String,String>> fuelTypeMapList = new List<Map<String,String>>();
            for(Energy_Use_Fuel_Type__mdt fuelTypeVar:fuelTypeMetaList){
                Map<String,String> fuelTypeMap = new Map<String,String>();
                if(fuelTypeVar.Scope_Number__c == scopeVar){
                    fuelTypeMap.put('fuelType' , fueltypeVar.Fuel_Type__c);
                    fuelTypeMap.put('ApplicabilityPicklistLabel' , fuelTypeVar.Applicability_Picklist_Label__c);
                    fuelTypeMap.put('ApplicabilityValues' , fuelTypeVar.Applicability_Values__c);
                    fuelTypeMap.put('showNotApplicableForRenewable' , String.valueOf(fuelTypeVar.Show_Not_Applicable_For_Renewable__c));                  
                    fuelTypeMap.put('FuelTypeAccordionLabel' , fuelTypeVar.MasterLabel);
                    fuelTypeMap.put('uOMOptions' , fuelTypeVar.UOM_Options__c);
                    fuelTypeMap.put('renewableEnergyType' , fuelTypeVar.Renewable_Energy_Type__c);
                    fuelTypeMap.put('isSectionOpen',String.valueOf(fuelTypeVar.isSectionOpen__c));
                    
                    if(String.isNotBlank(fuelTypeVar.Refrigerant_Emissions_Factor__c) && refEmissionMap?.get(fuelTypeVar.Refrigerant_Emissions_Factor__c) != null){
                        fuelTypeMap.put('refrigerantEmissionsFactor',refEmissionMap.get(fuelTypeVar.Refrigerant_Emissions_Factor__c)); 
                    }
                    //fuelTypeMap.put('refrigerantEmissionsFactor',fuelTypeVar.Refrigerant_Emissions_Factor__c);
                    fuelTypeMapList.add(fuelTypeMap);
                }
            }
            scopeWrapperVar.fuelTypesList = fuelTypeMapList;
            resultList.add(scopeWrapperVar);
        }
        tempMetadataWrapper.scopeMetadataWrapperData = resultList;
        //return resultList;
        return tempMetadataWrapper;
    }
    
    //get the refrigerant emission factors from Emission Factor object based on Country and State of Site Information
    public static Map<String,String> getRefEmissionFactor(StnryAssetEnvrSrc siteInfo){
        // if(string.isBlank(siteInfo)) return null;
        if(siteInfo == null) return null;
        String query = '';
        String currentCountry = siteInfo.Country;
        String status = 'Approved';
        
        if(siteInfo.Country == 'US'){
            String currentState = siteInfo.State;
            query = 'SELECT Id, Name, CFC_R22_Refrigerant_Emissions_Factor__c, HFC_125_Refrigerant_Emissions_Factor__c, HFC_134a_Refrigerant_Emissions_Factor__c, HFC_R32_Refrigerant_Emissions_Factor__c, HFC_R407c_Refrigerant_Emissions_Factor__c,HFC_R410a_Refrigerant_Emissions_Factor__c FROM Emission_Factor__c WHERE Country__c=:currentCountry AND State__c=:currentState AND Status__c=:status LIMIT 1';
        }
        else{
            query = 'SELECT Id, Name, CFC_R22_Refrigerant_Emissions_Factor__c, HFC_125_Refrigerant_Emissions_Factor__c, HFC_134a_Refrigerant_Emissions_Factor__c, HFC_R32_Refrigerant_Emissions_Factor__c, HFC_R407c_Refrigerant_Emissions_Factor__c,HFC_R410a_Refrigerant_Emissions_Factor__c FROM Emission_Factor__c WHERE Country__c=:currentCountry AND Status__c=:status LIMIT 1';
        }
        List<Emission_Factor__c> lstEmissionFactors = Database.query(query);
        if(lstEmissionFactors == null || lstEmissionFactors.isEmpty()) return null;
        Emission_Factor__c refEmission = lstEmissionFactors[0];
        Map<String,String> refEmissionMap = new Map<String,String>();
        refEmissionMap.put('CFC-R22', refEmission.CFC_R22_Refrigerant_Emissions_Factor__c);
        refEmissionMap.put('HFC-125', refEmission.HFC_125_Refrigerant_Emissions_Factor__c);
        refEmissionMap.put('HFC-134a', refEmission.HFC_134a_Refrigerant_Emissions_Factor__c);
        refEmissionMap.put('HFC-R32', refEmission.HFC_R32_Refrigerant_Emissions_Factor__c);
        refEmissionMap.put('HFC-R407c', refEmission.HFC_R407c_Refrigerant_Emissions_Factor__c);
        refEmissionMap.put('HFC-R410a', refEmission.HFC_R410a_Refrigerant_Emissions_Factor__c);
        return refEmissionMap;
    }
    
    /*Create the energy use records based on the details captured from all the child components of the LWC Component.
      Details are received as List of Wrapper objects where each wrapper object represents the details captured from a 
      single child component.
      Example Wrapper object received from LWC for one fuel type:
              (EnergyUseWrapperFromJS:[applicabilityValue=Applicable, 
                                       energyUseRecord=StnryAssetEnrgyUse:{StnryAssetEnvrSrcId=0ph6w000000Cc1zAAC, 
                                                                           Procurement_Emissions_Factor_Set__c=0pT6w0000008OLJEA2, 
                                                                           Name=Test Energy Use New, 
                                                                           FuelConsumption=100, 
                                                                           FuelType=Electricity, 
                                                                           FuelConsumptionUnit=kWh, 
                                                                           StartDate=2024-07-25 00:00:00, 
                                                                           EndDate=2024-07-26 00:00:00, 
                                                                           I_have_reviewed_all_fields_and_data__c=true}, 
                                       fileDocumentId=0696w000001mGsxAAE, 
                                       fuelTypeLabel=Electricity
                                       ]
               )
  
       Example Wrapper object after energy use record creation:
               (EnergyUseWrapperFromJS:[applicabilityValue=Applicable, 
                                        energyUseRecord=StnryAssetEnrgyUse:{StnryAssetEnvrSrcId=0ph6w000000Cc1zAAC, 
                                                                            Procurement_Emissions_Factor_Set__c=0pT6w0000008OLJEA2, 
                                                                            Name=Test Energy Use New, 
                                                                            FuelConsumption=100, 
                                                                            FuelType=Electricity, 
                                                                            FuelConsumptionUnit=kWh, 
                                                                            StartDate=2024-07-25 00:00:00, 
                                                                            EndDate=2024-07-26 00:00:00, 
                                                                            I_have_reviewed_all_fields_and_data__c=true, 
                                                                            Id=7LK6w000000CjfaGAC}, 
                                        fileDocumentId=0696w000001mGsxAAE,  
                                        fuelTypeLabel=Electricity
                                        ]
                 )
    */
    @AuraEnabled
    public static List<StnryAssetEnrgyUse> createEnergyUseRecord(List<EnergyUseWrapperFromJS> energyUseWrapper){
        //System.debug('wrapper from js '+ energyUseWrapper);
        List<StnryAssetEnrgyUse> energyUseRecordsToInsert = new List<StnryAssetEnrgyUse>();
        List<String> failureMessages = new List<String>();
        try{
            for(EnergyUseWrapperFromJS temp : energyUseWrapper){
                if(temp.applicabilityValue == 'Applicable'){
                    energyUseRecordsToInsert.add(temp.energyUseRecord);
                }
            }
            Database.SaveResult[] energyUseRecordsResultList = Database.insert(energyUseRecordsToInsert, false);
            for(Database.SaveResult sr : energyUseRecordsResultList){
                if(!sr.isSuccess()){
                    for(Database.Error err : sr.getErrors()) {
                       failureMessages.add('Failed to create StnryAssetEnrgyUse records : ' + err.getMessage());
                    }
                }
            }
            //System.debug('eu records created are '+ energyUseRecordsToInsert);
            //System.debug('wrapper after eu creation '+ energyUseWrapper);
            List<Energy_Use_Data_Log__c> dataLogsToInsert = new List<Energy_Use_Data_Log__c>();
            for(EnergyUseWrapperFromJS temp : energyUseWrapper){
                Energy_Use_Data_Log__c ed = new Energy_Use_Data_Log__c();
                ed.Site_Information__c = temp.energyUseRecord.StnryAssetEnvrSrcId;
                ed.Stationary_Asset_Energy_Use__c = temp.energyUseRecord.Id;
                ed.Fuel_Type__c = temp.fuelTypeLabel;
                ed.Fuel_Consumption__c = temp.energyUseRecord.FuelConsumption;
                ed.Consumption_Unit__c = temp.energyUseRecord.FuelConsumptionUnit;
                ed.Option_Selected__c = temp.applicabilityValue;
                ed.Start_Date__c = temp.energyUseRecord.StartDate;
                ed.End_Date__c = temp.energyUseRecord.EndDate;
                ed.NZC_Month_Selected__c = temp.energyUseRecord.NZC_Month__c;
                ed.Comments__c = temp.energyUseRecord.Comments__c;
                ed.User_Time__c = UserInfo.getUserName() + ' ' + Datetime.now();
                
                dataLogsToInsert.add(ed);
            }
            
            linkFile(energyUseWrapper);
            
            if(!dataLogsToInsert.isEmpty()){
                insert dataLogsToInsert;
            }
            
            if(!failureMessages.isEmpty()){
                NZCErrorLog.logErrors(failureMessages);
            }
        }
        catch(Exception ex) {
            NZCErrorLog.logError('Failed to create StnryAssetEnrgyUse records : ' + ex.getMessage());
            //System.debug('error on '+ ex.getLineNumber() + ex.getMessage());
            return null;
        }
        return energyUseRecordsToInsert;
    }
    
    //linking the uploaded file to an energy use record
    @AuraEnabled
    public static void linkFile(List<EnergyUseWrapperFromJS> energyUseWrapper){ 
        List<ContentDocumentLink> contentDocumentListToInsert = new List<ContentDocumentLink>();
        for(EnergyUseWrapperFromJS temp: energyUseWrapper){
            if(temp.energyUseRecord.Id != null && String.isNotBlank(temp.fileDocumentId)){
                List<String> fileStringList = temp.fileDocumentId.split(',');
                for(String s:fileStringList){
                   ContentDocumentLink cdl = new ContentDocumentLink();
                   cdl.ContentDocumentId = s;
                   cdl.LinkedEntityId = temp.energyUseRecord.Id;
                   contentDocumentListToInsert.add(cdl);
                }
                //System.debug('contentDocumentListToInsert:'+contentDocumentListToInsert);
            }
        }
        try{    
            if(!contentDocumentListToInsert.isEmpty() && ContentDocumentLink.sObjectType.getDescribe(SObjectDescribeOptions.DEFERRED).isCreateable()){
                insert contentDocumentListToInsert;    
            }
        }
        catch(Exception e){
            NZCErrorLog.logError('Failed to link file to StnryAssetEnrgyUse record : ' + e.getMessage());
        }
    }
    
    public class EnergyUseMetadataWrapper{
        @AuraEnabled
        public boolean approvedEmissionFactorsFound = true;
        @AuraEnabled
        public List<ScopeMetadataWrapper> scopeMetadataWrapperData;
    }
    
    public class ScopeMetadataWrapper{
        @AuraEnabled
        public String scopeLabel;
        @AuraEnabled
        public List<Map<String,String>> fuelTypesList;    
    }
    
    public class EnergyUseWrapperFromJS{
        @AuraEnabled
        public StnryAssetEnrgyUse energyUseRecord {get; set;}
        @AuraEnabled
        public String fileDocumentId {get; set;}
        @AuraEnabled
        public String applicabilityValue {get; set;}
        @AuraEnabled
        public String fuelTypeLabel {get; set;}
    }
}