force-app/main/default/objects/Emission_Factor__c/Emission_Factor__c.object-meta.xml
<CustomObject>
    <description>HT: Created for NZC Implementation UC003_US01, created to store different type of emission factors.</description>
    <label>Emission Factor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Emission Factors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Emission_Factor__c/fields/CFC_R22_Refrigerant_Emissions_Factor__c.field-meta.xml
<CustomField>
    <fullName>CFC_R22_Refrigerant_Emissions_Factor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CFC-R22 Refrigerant Emissions Factor</label>
    <referenceTo>RefrigerantEmssnFctr</referenceTo>
    <relationshipName>Load_Emission_Factors1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Emission_Factor__c/fields/HFC_125_Refrigerant_Emissions_Factor__c.field-meta.xml
<CustomField>
    <fullName>HFC_125_Refrigerant_Emissions_Factor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HFC-125 Refrigerant Emissions Factor</label>
    <referenceTo>RefrigerantEmssnFctr</referenceTo>
    <relationshipLabel>Emission Factors (HFC - 125 Refrigerant Emissions Factor)</relationshipLabel>
    <relationshipName>Load_Emission_Factors5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Emission_Factor__c/fields/HFC_134a_Refrigerant_Emissions_Factor__c.field-meta.xml
<CustomField>
    <fullName>HFC_134a_Refrigerant_Emissions_Factor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HFC-134a Refrigerant Emissions Factor</label>
    <referenceTo>RefrigerantEmssnFctr</referenceTo>
    <relationshipLabel>Emission Factors (HFC - 134a Refrigerant Emissions Factor)</relationshipLabel>
    <relationshipName>Load_Emission_Factors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Emission_Factor__c/fields/HFC_R32_Refrigerant_Emissions_Factor__c.field-meta.xml
<CustomField>
    <fullName>HFC_R32_Refrigerant_Emissions_Factor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HFC-R32 Refrigerant Emissions Factor</label>
    <referenceTo>RefrigerantEmssnFctr</referenceTo>
    <relationshipName>Load_Emission_Factors4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Emission_Factor__c/fields/HFC_R407c_Refrigerant_Emissions_Factor__c.field-meta.xml
<CustomField>
    <fullName>HFC_R407c_Refrigerant_Emissions_Factor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HFC-R407c Refrigerant Emissions Factor</label>
    <referenceTo>RefrigerantEmssnFctr</referenceTo>
    <relationshipName>Load_Emission_Factors3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Emission_Factor__c/fields/HFC_R410a_Refrigerant_Emissions_Factor__c.field-meta.xml
<CustomField>
    <fullName>HFC_R410a_Refrigerant_Emissions_Factor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HFC-R410a Refrigerant Emissions Factor</label>
    <referenceTo>RefrigerantEmssnFctr</referenceTo>
    <relationshipName>Load_Emission_Factors2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Emission_Factor__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Pending for approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Revised</fullName>
            </value>
            <value>
                <fullName>Pending with Level 2 Approver</fullName>
                <isActive>false</isActive>
                <label>Pending with Level 2 Approver</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Energy_Use_Fuel_Type__mdt/Energy_Use_Fuel_Type__mdt.object-meta.xml
<CustomObject>
    <description>HT: Created for NZC Implementation, UC003_US02, UC003_US12, UC003_US15, created to store the fuel types which are visible on the Energy Use creation form for Data Processors.</description>
    <label>Energy Use Fuel Type</label>
    <pluralLabel>Energy Use Fuel Types</pluralLabel>
</CustomObject>

force-app/main/default/objects/Energy_Use_Fuel_Type__mdt/fields/Applicability_Picklist_Label__c.field-meta.xml
<CustomField>
    <fullName>Applicability_Picklist_Label__c</fullName>
    <label>Applicability Picklist Label</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Energy_Use_Fuel_Type__mdt/fields/Applicability_Values__c.field-meta.xml
<CustomField>
    <fullName>Applicability_Values__c</fullName>
    <label>Applicability Values</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Energy_Use_Fuel_Type__mdt/fields/Fuel_Type__c.field-meta.xml
<CustomField>
    <fullName>Fuel_Type__c</fullName>
    <label>Fuel Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Energy_Use_Fuel_Type__mdt/fields/isSectionOpen__c.field-meta.xml
<CustomField>
    <fullName>isSectionOpen__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isSectionOpen</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Energy_Use_Fuel_Type__mdt/fields/Refrigerant_Emissions_Factor__c.field-meta.xml
<CustomField>
    <fullName>Refrigerant_Emissions_Factor__c</fullName>
    <label>Refrigerant Emissions Factor</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Energy_Use_Fuel_Type__mdt/fields/Renewable_Energy_Type__c.field-meta.xml
<CustomField>
    <fullName>Renewable_Energy_Type__c</fullName>
    <label>Renewable Energy Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Energy_Use_Fuel_Type__mdt/fields/Scope_Number__c.field-meta.xml
<CustomField>
    <fullName>Scope_Number__c</fullName>
    <label>Scope Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Energy_Use_Fuel_Type__mdt/fields/Show_for_ULA__c.field-meta.xml
<CustomField>
    <fullName>Show_for_ULA__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Harshvardhan: Created this checkbox field for the ULA requirement. If this field is true, then the corresponding metadata record(Fuel Type) will be shown on the Data Entry form as part of ULA.</description>
    <label>Show for ULA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Energy_Use_Fuel_Type__mdt/fields/Show_Not_Applicable_For_Renewable__c.field-meta.xml
<CustomField>
    <fullName>Show_Not_Applicable_For_Renewable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Not Applicable For Renewable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Energy_Use_Fuel_Type__mdt/fields/UOM_Options__c.field-meta.xml
<CustomField>
    <fullName>UOM_Options__c</fullName>
    <label>UOM Options</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StnryAssetEnvrSrc/fields/NZC_ULA__c.field-meta.xml
<CustomField>
    <fullName>NZC_ULA__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Harshvardhan: Created this checkbox field for the ULA requirement. If this field is true, then the site information is ULA.</description>
    <label>ULA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StnryAssetEnvrSrc/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>VB, Venkat: Created for NZC Implementation UC002_US01
Purpose: To Capture the Approval Status of the record.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Pending for Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Revised</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EnergyUseControllerUpdatedOLD.cls
public with sharing class EnergyUseControllerUpdatedOLD {
    /******************************************************************************
Class Name: EnergyUseControllerUpdatedOLD
Created By : Harshvardhan Tiwari
Created : 11-Oct-23
Description : Created to get the metadata records to arrange them and show them on the data entry form, 
send the energy use record for approval, link the uploaded file to the record and to link the refrigerant record with
its emission factor
*************************************************************************/

    //get the custom metadata records to pass it into lwc and show it as a form
    @AuraEnabled(cacheable=true)
    public static EnergyUseControllerUpdatedOLD.EnergyUseMetadataWrapper getMetadataInformation(String parentSiteInfo){
    //public static List<EnergyUseControllerUpdated.ScopeMetadataWrapper> getMetadataInformation(String parentSiteInfo){
        if(String.isBlank(parentSiteInfo)) return null;
        EnergyUseMetadataWrapper tempMetadataWrapper = new EnergyUseMetadataWrapper();
        StnryAssetEnvrSrc siteInfo = [SELECT Id, NZC_ULA__c, Name, Country, State FROM StnryAssetEnvrSrc WHERE Id=:parentSiteInfo LIMIT 1];
        if(siteInfo == null){
            return null;
        } 
        //refrigerant emission factor logic starts
        Map<String,String> refEmissionMap = getRefEmissionFactor(siteInfo);
        //refrigerant emission factor logic ends
        
        if(refEmissionMap == null || refEmissionMap.keySet().isEmpty()){
            tempMetadataWrapper.approvedEmissionFactorsFound = false;
            tempMetadataWrapper.scopeMetadataWrapperData = null;
            return tempMetadataWrapper;
        }
        
        List<Energy_Use_Fuel_Type__mdt> fuelTypeMetaList = new List<Energy_Use_Fuel_Type__mdt>();

 
        //else{
        fuelTypeMetaList = [SELECT Fuel_Type__c,
                            MasterLabel,
                            Applicability_Picklist_Label__c,
                            Applicability_Values__c,
                            Show_Not_Applicable_For_Renewable__c,
                            UOM_Options__c,
                            Scope_Number__c,
                            Refrigerant_Emissions_Factor__c,
                            isSectionOpen__c,
                            Renewable_Energy_Type__c,
                            Order__c ,
                            Show_for_ULA__c                                            
                            FROM Energy_Use_Fuel_Type__mdt
                            WHERE Show_for_ULA__c = :siteInfo.NZC_ULA__c
                            ORDER BY Order__c ASC];

        List<EnergyUseControllerUpdatedOLD.ScopeMetadataWrapper> resultList = new List<ScopeMetadataWrapper>();
        Set<String> scopeList = new Set<String>();
        for(Energy_Use_Fuel_Type__mdt eft : fuelTypeMetaList){
            scopeList.add(eft.Scope_Number__c);
        }
        for(String scopeVar:scopeList){
            ScopeMetadataWrapper scopeWrapperVar = new ScopeMetadataWrapper();
            scopeWrapperVar.scopeLabel = scopeVar;
            List<Map<String,String>> fuelTypeMapList = new List<Map<String,String>>();
            for(Energy_Use_Fuel_Type__mdt fuelTypeVar:fuelTypeMetaList){
                Map<String,String> fuelTypeMap = new Map<String,String>();
                if(fuelTypeVar.Scope_Number__c == scopeVar){
                    fuelTypeMap.put('fuelType' , fueltypeVar.Fuel_Type__c);
                    fuelTypeMap.put('ApplicabilityPicklistLabel' , fuelTypeVar.Applicability_Picklist_Label__c);
                    fuelTypeMap.put('ApplicabilityValues' , fuelTypeVar.Applicability_Values__c);
                    fuelTypeMap.put('showNotApplicableForRenewable' , String.valueOf(fuelTypeVar.Show_Not_Applicable_For_Renewable__c));                  
                    fuelTypeMap.put('FuelTypeAccordionLabel' , fuelTypeVar.MasterLabel);
                    fuelTypeMap.put('uOMOptions' , fuelTypeVar.UOM_Options__c);
                    fuelTypeMap.put('renewableEnergyType' , fuelTypeVar.Renewable_Energy_Type__c);
                    fuelTypeMap.put('isSectionOpen',String.valueOf(fuelTypeVar.isSectionOpen__c));
                   
                    if(String.isNotBlank(fuelTypeVar.Refrigerant_Emissions_Factor__c) && refEmissionMap?.get(fuelTypeVar.Refrigerant_Emissions_Factor__c) != null){
                        fuelTypeMap.put('refrigerantEmissionsFactor',refEmissionMap.get(fuelTypeVar.Refrigerant_Emissions_Factor__c)); 
                    }
                    //fuelTypeMap.put('refrigerantEmissionsFactor',fuelTypeVar.Refrigerant_Emissions_Factor__c);
                    fuelTypeMapList.add(fuelTypeMap);
                }
            }
            scopeWrapperVar.fuelTypesList = fuelTypeMapList;
            resultList.add(scopeWrapperVar);
        }
        tempMetadataWrapper.scopeMetadataWrapperData = resultList;
        //return resultList;
        return tempMetadataWrapper;
    }
    public static Map<String,String> getRefEmissionFactor(StnryAssetEnvrSrc siteInfo){
       // if(string.isBlank(siteInfo)) return null;
        if(siteInfo == null) return null;
        String query = '';
        String currentCountry = siteInfo.Country;
        String status = 'Approved';
        
        if(siteInfo.Country == 'US'){
            String currentState = siteInfo.State;
            query = 'SELECT Id, Name, CFC_R22_Refrigerant_Emissions_Factor__c, HFC_125_Refrigerant_Emissions_Factor__c, HFC_134a_Refrigerant_Emissions_Factor__c, HFC_R32_Refrigerant_Emissions_Factor__c, HFC_R407c_Refrigerant_Emissions_Factor__c,HFC_R410a_Refrigerant_Emissions_Factor__c FROM Emission_Factor__c WHERE Country__c=:currentCountry AND State__c=:currentState AND Status__c=:status LIMIT 1';
        }
        else{
            query = 'SELECT Id, Name, CFC_R22_Refrigerant_Emissions_Factor__c, HFC_125_Refrigerant_Emissions_Factor__c, HFC_134a_Refrigerant_Emissions_Factor__c, HFC_R32_Refrigerant_Emissions_Factor__c, HFC_R407c_Refrigerant_Emissions_Factor__c,HFC_R410a_Refrigerant_Emissions_Factor__c FROM Emission_Factor__c WHERE Country__c=:currentCountry AND Status__c=:status LIMIT 1';
        }
        List<Emission_Factor__c> lstEmissionFactors = Database.query(query);
        if(lstEmissionFactors == null || lstEmissionFactors.isEmpty()) return null;
        Emission_Factor__c refEmission = lstEmissionFactors[0];
        Map<String,String> refEmissionMap = new Map<String,String>();
        refEmissionMap.put('CFC-R22', refEmission.CFC_R22_Refrigerant_Emissions_Factor__c);
        refEmissionMap.put('HFC-125', refEmission.HFC_125_Refrigerant_Emissions_Factor__c);
        refEmissionMap.put('HFC-134a', refEmission.HFC_134a_Refrigerant_Emissions_Factor__c);
        refEmissionMap.put('HFC-R32', refEmission.HFC_R32_Refrigerant_Emissions_Factor__c);
        refEmissionMap.put('HFC-R407c', refEmission.HFC_R407c_Refrigerant_Emissions_Factor__c);
        refEmissionMap.put('HFC-R410a', refEmission.HFC_R410a_Refrigerant_Emissions_Factor__c);
        return refEmissionMap;
    }
    
    //linking the uploaded file to a record
    @AuraEnabled
    public static String linkFile(String documentId, String energyUseRecordId){
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = documentId;
        cdl.LinkedEntityId = energyUseRecordId;
        try{
            if(ContentDocumentLink.sObjectType.getDescribe(SObjectDescribeOptions.DEFERRED).isCreateable()){
                Insert cdl;    
            }
            
        }
        catch(Exception e){
            return 'File not linked';
        }
        
        return 'File linked successfully!';
    }
    
    public class EnergyUseMetadataWrapper{
        @AuraEnabled
        public boolean approvedEmissionFactorsFound = true;
        @AuraEnabled
        public List<ScopeMetadataWrapper> scopeMetadataWrapperData;
    }
    
    public class ScopeMetadataWrapper{
        @AuraEnabled
        public String scopeLabel;
        @AuraEnabled
        public List<Map<String,String>> fuelTypesList;
        
    }
}