force-app/main/default/objects/atl_Resource__c/atl_Resource__c.object-meta.xml
<CustomObject>
    <description>A task, template, guide, or training related to a phase, role, and/or technology.</description>
    <label>Atlas Resource</label>
    <nameField>
        <label>Atlas Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Atlas Resources</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/atl_Resource__c/fields/atl_AvailableForSearch__c.field-meta.xml
<CustomField>
    <fullName>atl_AvailableForSearch__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Available for Search</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/atl_Resource__c/fields/atl_Cognizant_Role__c.field-meta.xml
<CustomField>
    <fullName>atl_Cognizant_Role__c</fullName>
    <label>Cognizant Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
                <label>All Roles</label>
            </value>
            <value>
                <fullName>Engagement Lead</fullName>
            </value>
            <value>
                <fullName>Portfolio Lead</fullName>
            </value>
            <value>
                <fullName>Delivery Excellence</fullName>
            </value>
            <value>
                <fullName>Product Owner</fullName>
            </value>
            <value>
                <fullName>Scrum Master</fullName>
            </value>
            <value>
                <fullName>Program Lead</fullName>
            </value>
            <value>
                <fullName>Senior Technology Architect</fullName>
            </value>
            <value>
                <fullName>Technology Architect</fullName>
            </value>
            <value>
                <fullName>Technical Lead</fullName>
            </value>
            <value>
                <fullName>Senior Developer</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Test Lead</fullName>
            </value>
            <value>
                <fullName>Tester</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/atl_Resource__c/fields/atl_cognizant_stage__c.field-meta.xml
<CustomField>
    <fullName>atl_cognizant_stage__c</fullName>
    <inlineHelpText>If you edit this field, remember to edit Cognizant Stage Display as well!</inlineHelpText>
    <label>Cognizant Stage</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
                <label>All Stages</label>
            </value>
            <value>
                <fullName>Stage0</fullName>
                <label>Stage 0: Sales</label>
            </value>
            <value>
                <fullName>Gate0</fullName>
                <label>Sale Qualified</label>
            </value>
            <value>
                <fullName>Stage1</fullName>
                <label>Stage 1: Scoping, Transition &amp; Project Initialization</label>
            </value>
            <value>
                <fullName>Gate1</fullName>
                <label>Sales To Delivery Handoff</label>
            </value>
            <value>
                <fullName>Stage2</fullName>
                <label>Stage 2: Project Kickoff &amp; High Level Design</label>
            </value>
            <value>
                <fullName>Gate2</fullName>
                <label>Project Success Confirmation</label>
            </value>
            <value>
                <fullName>Stage3</fullName>
                <label>Stage 3: Detailed Design &amp; Build</label>
            </value>
            <value>
                <fullName>Gate3</fullName>
                <label>Configuration &amp; UAT Test Plan Sign Off</label>
            </value>
            <value>
                <fullName>Stage4</fullName>
                <label>Stage 4: Solution Validation</label>
            </value>
            <value>
                <fullName>Gate4</fullName>
                <label>Go/No-Go</label>
            </value>
            <value>
                <fullName>Stage5</fullName>
                <label>Stage 5: Go Live</label>
            </value>
            <value>
                <fullName>Gate5</fullName>
                <label>Project Closure &amp; Next Phase Assessment</label>
            </value>
            <value>
                <fullName>Stage6</fullName>
                <label>Stage 6: Application Support</label>
            </value>
            <value>
                <fullName>Overlay1</fullName>
                <label>Scope, Timeline &amp; Budget Management</label>
            </value>
            <value>
                <fullName>Overlay2</fullName>
                <label>Data Migration &amp; Integration</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/atl_Resource__c/fields/atl_DisplayName__c.field-meta.xml
<CustomField>
    <fullName>atl_DisplayName__c</fullName>
    <label>Display Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/atl_Resource__c/fields/atl_DocType__c.field-meta.xml
<CustomField>
    <fullName>atl_DocType__c</fullName>
    <label>Doc Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PDF</fullName>
            </value>
            <value>
                <fullName>PowerPoint</fullName>
            </value>
            <value>
                <fullName>Word Document</fullName>
            </value>
            <value>
                <fullName>Excel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/atl_Resource__c/fields/atl_Link__c.field-meta.xml
<CustomField>
    <fullName>atl_Link__c</fullName>
    <label>Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/atl_Resource__c/fields/atl_owner__c.field-meta.xml
<CustomField>
    <fullName>atl_owner__c</fullName>
    <description>CoP that owns this activity/template/guide/training</description>
    <inlineHelpText>CoP that owns this activity/template/guide/training</inlineHelpText>
    <label>Owner</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
                <label>All Owners</label>
            </value>
            <value>
                <fullName>Advisory</fullName>
            </value>
            <value>
                <fullName>Application Support</fullName>
            </value>
            <value>
                <fullName>Architecture Team</fullName>
            </value>
            <value>
                <fullName>BACoP</fullName>
            </value>
            <value>
                <fullName>CLM CoP</fullName>
            </value>
            <value>
                <fullName>Cognizant Delivery</fullName>
            </value>
            <value>
                <fullName>Commerce CoP</fullName>
            </value>
            <value>
                <fullName>Conga CoP</fullName>
            </value>
            <value>
                <fullName>Data Engineering Team</fullName>
            </value>
            <value>
                <fullName>Delivery Partner</fullName>
            </value>
            <value>
                <fullName>Deployment Team</fullName>
            </value>
            <value>
                <fullName>DocuSign CoP</fullName>
            </value>
            <value>
                <fullName>Emerging Billing CoP</fullName>
            </value>
            <value>
                <fullName>gotransverse CoP</fullName>
            </value>
            <value>
                <fullName>ICon Leadership</fullName>
            </value>
            <value>
                <fullName>Integration CoP</fullName>
            </value>
            <value>
                <fullName>IP Team</fullName>
            </value>
            <value>
                <fullName>Legal Team</fullName>
            </value>
            <value>
                <fullName>Logik CoP</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>NZC CoP</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Partner Engagement</fullName>
            </value>
            <value>
                <fullName>PMCoP</fullName>
            </value>
            <value>
                <fullName>QACoP</fullName>
            </value>
            <value>
                <fullName>Sales Team</fullName>
            </value>
            <value>
                <fullName>Salesforce CoP</fullName>
            </value>
            <value>
                <fullName>Software Engineering Team</fullName>
            </value>
            <value>
                <fullName>Solution Engineering Team</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/atl_Resource__c/fields/atl_Role__c.field-meta.xml
<CustomField>
    <fullName>atl_Role__c</fullName>
    <label>Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
                <label>All Roles</label>
            </value>
            <value>
                <fullName>Application Support Specialist</fullName>
            </value>
            <value>
                <fullName>Business Analyst</fullName>
            </value>
            <value>
                <fullName>Data Engineer</fullName>
            </value>
            <value>
                <fullName>Delivery Partner</fullName>
            </value>
            <value>
                <fullName>Deployment Specialist</fullName>
            </value>
            <value>
                <fullName>Implementation Consultant</fullName>
            </value>
            <value>
                <fullName>Integration Engineer</fullName>
            </value>
            <value>
                <fullName>Practice Lead</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Quality Assurance Analyst</fullName>
            </value>
            <value>
                <fullName>Sales Executive</fullName>
            </value>
            <value>
                <fullName>Software Engineer</fullName>
            </value>
            <value>
                <fullName>Solution Architect</fullName>
            </value>
            <value>
                <fullName>Solution Engineer</fullName>
            </value>
            <value>
                <fullName>Staffing</fullName>
            </value>
            <value>
                <fullName>Team Lead</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
                <isActive>false</isActive>
                <label>Client</label>
            </value>
            <value>
                <fullName>Integration Engineer Lead</fullName>
                <isActive>false</isActive>
                <label>Integration Engineer Lead</label>
            </value>
            <value>
                <fullName>Production Success Specialist</fullName>
                <isActive>false</isActive>
                <label>Production Success Specialist</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/atl_Resource__c/fields/atl_SalesforceFileId__c.field-meta.xml
<CustomField>
    <fullName>atl_SalesforceFileId__c</fullName>
    <label>Salesforce File Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/atl_Resource__c/fields/atl_Stage__c.field-meta.xml
<CustomField>
    <fullName>atl_Stage__c</fullName>
    <inlineHelpText>If you edit this field, remember to edit Stage Display as well!</inlineHelpText>
    <label>Stage</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
                <label>All Stages</label>
            </value>
            <value>
                <fullName>Stage0</fullName>
                <label>Stage 0: Sales</label>
            </value>
            <value>
                <fullName>Gate0</fullName>
                <label>Sale Qualified</label>
            </value>
            <value>
                <fullName>Stage1</fullName>
                <label>Stage 1: Scoping &amp; Project Initialization</label>
            </value>
            <value>
                <fullName>Gate1</fullName>
                <label>Sales To Delivery Handoff</label>
            </value>
            <value>
                <fullName>Stage2</fullName>
                <label>Stage 2: Project Kickoff &amp; High Level Design</label>
            </value>
            <value>
                <fullName>Gate2</fullName>
                <label>Project Success Confirmation</label>
            </value>
            <value>
                <fullName>Stage3</fullName>
                <label>Stage 3: Detailed Design &amp; Build</label>
            </value>
            <value>
                <fullName>Gate3</fullName>
                <label>Configuration &amp; UAT Test Plan Sign Off</label>
            </value>
            <value>
                <fullName>Stage4</fullName>
                <label>Stage 4: Solution Validation</label>
            </value>
            <value>
                <fullName>Gate4</fullName>
                <label>Go/No-Go</label>
            </value>
            <value>
                <fullName>Stage5</fullName>
                <label>Stage 5: Go Live</label>
            </value>
            <value>
                <fullName>Gate5</fullName>
                <label>Project Closure &amp; Next Phase Assessment</label>
            </value>
            <value>
                <fullName>Stage6</fullName>
                <label>Stage 6: Application Support</label>
            </value>
            <value>
                <fullName>Overlay1</fullName>
                <label>Scope, Timeline &amp; Budget Management</label>
            </value>
            <value>
                <fullName>Overlay2</fullName>
                <label>Data Migration &amp; Integration</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/atl_Resource__c/recordTypes/Activity.recordType-meta.xml
<RecordType>
    <fullName>Activity</fullName>
    <active>true</active>
    <label>Activity</label>
</RecordType>

force-app/main/default/objects/atl_Resource__c/recordTypes/TemplateOrGuide.recordType-meta.xml
<RecordType>
    <fullName>TemplateOrGuide</fullName>
    <active>true</active>
    <label>Template or Guide</label>
</RecordType>

force-app/main/default/objects/atl_Resource__c/recordTypes/Training.recordType-meta.xml
<RecordType>
    <fullName>Training</fullName>
    <active>true</active>
    <label>Training</label>
</RecordType>

force-app/main/default/classes/atl_MainFilterApexController.cls
public class atl_MainFilterApexController {
    
    @AuraEnabled
    // Initial resource query + record type retrieval
    public static Map<String, Object> getResources() {
        // Get all record type ids
        Id activityId = Schema.SObjectType.atl_Resource__c.getRecordTypeInfosByDeveloperName().get('Activity').getRecordTypeId();
        Id templateGuideId = Schema.SObjectType.atl_Resource__c.getRecordTypeInfosByDeveloperName().get('TemplateOrGuide').getRecordTypeId();
        Id trainingId = Schema.SObjectType.atl_Resource__c.getRecordTypeInfosByDeveloperName().get('Training').getRecordTypeId();
        // Get all resources
        List<atl_Resource__c> resources = [SELECT Name, atl_AvailableForSearch__c, atl_DisplayName__c, atl_DocType__c, atl_Link__c, atl_owner__c,
                                           atl_Role__c, atl_Cognizant_Role__c, atl_SalesforceFileId__c, atl_Stage__c, atl_cognizant_stage__c, atl_Status__c, atl_Sequence__c, 
                                           RecordTypeId, atl_Technology__c, atl_Cognizant_Technology__c, atl_TrainingType__c, atl_ResourceType__c, atl_Advisory_Role__c, 
                                           atl_Advisory_Stage__c, atl_Advisory_Offering__c, atl_Project_Type__c FROM atl_Resource__c ORDER BY atl_Sequence__c ASC];
        return new Map<String, Object>{
            'activityId' => activityId, 
            'templateGuideId' => templateGuideId,
            'trainingId' => trainingId,
            'resources' => resources
        };    
    }
    
    // This grabs the values for the stage picklist
    @AuraEnabled
    /* public static List<PicklistValue> getStageValues(String resourceType) {
        List<PicklistValue> stages = new List<PicklistValue>();
        if (resourceType.contains('/s/advisory')) {
            for (Schema.PicklistEntry stageVal :atl_Resource__c.atl_Advisory_Stage__c.getDescribe().getPicklistValues()) {
                PicklistValue val = new PicklistValue();
                val.label = stageVal.getLabel();
                val.value = stageVal.getValue();
                stages.add(val);
            }
        } else if (resourceType.contains('/s/atg-delivery')) {
            for (Schema.PicklistEntry stageVal :atl_Resource__c.atl_Stage__c.getDescribe().getPicklistValues()) {
                PicklistValue val = new PicklistValue();
                val.label = stageVal.getLabel();
                val.value = stageVal.getValue();
                stages.add(val);
            }
        } else if (resourceType.contains('/s/cognizant-delivery')) {
            for (Schema.PicklistEntry stageVal :atl_Resource__c.atl_cognizant_stage__c.getDescribe().getPicklistValues()) {
                PicklistValue val = new PicklistValue();
                val.label = stageVal.getLabel();
                val.value = stageVal.getValue();
                stages.add(val);
            }
        }

        return stages;
    } */ 
    public static List<PicklistValue> getStageValues(String resourceType) {
        List<PicklistValue> stages = new List<PicklistValue>();
		List<Schema.PicklistEntry> stageVals;
        if (resourceType.contains('/s/advisory')) {
			stageVals = atl_Resource__c.atl_Advisory_Stage__c.getDescribe().getPicklistValues();
        } else if (resourceType.contains('/s/atg-delivery')) {
            stageVals = atl_Resource__c.atl_Stage__c.getDescribe().getPicklistValues();
        } else if (resourceType.contains('/s/cognizant-delivery')) {
			stageVals = atl_Resource__c.atl_cognizant_stage__c.getDescribe().getPicklistValues();
        }
        if (stageVals != null) {
            for (Schema.PicklistEntry stageVal :stageVals) {
                PicklistValue val = new PicklistValue();
                val.label = stageVal.getLabel();
                val.value = stageVal.getValue();
                stages.add(val);
            }
        }
        return stages;
    }
    
    //@AuraEnabled
    public class PicklistValue {
        @AuraEnabled
        public String label;
        @AuraEnabled
        public String value;
    }
    
    @AuraEnabled
    // This grabs the values for the role picklist
    public static List<PicklistValue> getRoleValues(String resourceType) {
        List<PicklistValue> roles = new List<PicklistValue>();
        List<Schema.PicklistEntry> roleVals;
        if (resourceType.contains('/s/advisory')) {
			roleVals = atl_Resource__c.atl_Advisory_Role__c.getDescribe().getPicklistValues();
        } else if (resourceType.contains('/s/atg-delivery')) {
            roleVals = atl_Resource__c.atl_Role__c.getDescribe().getPicklistValues();
        } else if (resourceType.contains('/s/cognizant-delivery')) {
			roleVals = atl_Resource__c.atl_cognizant_Role__c.getDescribe().getPicklistValues();
        }
        if (roleVals != null) {
            for (Schema.PicklistEntry role :roleVals) {
                PicklistValue val = new PicklistValue();
				val.label = role.getLabel();
                val.value = role.getValue();
                roles.add(val);
            }
        }
        return roles;
    }
    
    @AuraEnabled
    // This grabs the values for the technology picklist
    public static List<PicklistValue> getTechValues(String resourceType) {
        List<PicklistValue> techs = new List<PicklistValue>();
        if (resourceType.contains('/s/advisory') ) {
            for (Schema.PicklistEntry tech :atl_Resource__c.atl_Advisory_Offering__c.getDescribe().getPicklistValues()) {
                PicklistValue val = new PicklistValue();
                val.label = tech.getLabel();
                val.value = tech.getValue();
                techs.add(val);
            }
        } else if (resourceType.contains('/s/atg-delivery')) {
            for (Schema.PicklistEntry tech :atl_Resource__c.atl_Technology__c.getDescribe().getPicklistValues()) {
                PicklistValue val = new PicklistValue();
                val.label = tech.getLabel();
                val.value = tech.getValue();
                techs.add(val);
            }
        } else if (resourceType.contains('/s/cognizant-delivery')) {
            for (Schema.PicklistEntry role :atl_Resource__c.atl_Cognizant_Technology__c.getDescribe().getPicklistValues()) {
                PicklistValue val = new PicklistValue();
                val.label = role.getLabel();
                val.value = role.getValue();
                techs.add(val);
            }
        }

        return techs;
    }
    
}