force-app/main/default/objects/AnnualEmssnInventory/fields/AEI_Data_Archival_Criteria_Check__c.field-meta.xml
<CustomField>
    <fullName>AEI_Data_Archival_Criteria_Check__c</fullName>
    <description>Formula field to check whether AEI is eligible for archival</description>
    <formula>TODAY() &gt;= AEI_Archival_Date__c</formula>
    <label>AEI Data Archival Criteria Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AnnualEmssnInventory/fields/Exclude_from_Archival__c.field-meta.xml
<CustomField>
    <fullName>Exclude_from_Archival__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox field if user wants to exclude his AEI from archival</description>
    <label>Exclude from Archival</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AnnualEmssnInventory/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>SB: Created as part of the user story PhII_UC007_US06
Purpose: To Capture the Status of the AEI</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Pending For Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Revised</fullName>
            </value>
            <value>
                <fullName>submitted for approval</fullName>
                <isActive>false</isActive>
                <label>submitted for approval</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NZCAnnualEmissionInventoryArchivalBatch.cls
/**********************************************************************************************************************************************************
Class Name: NZCAnnualEmissionInventoryArchivalBatch
Created By: Pranav Vibhandik
Created on: 28-May-2024 
Description: This class implements the Schedulable interface and is responsible for scheduling and initiating the batch job that deletes 
eligible Annual Emission Inventory records.

***********************************************************************************************************************************************************/

global class NZCAnnualEmissionInventoryArchivalBatch implements Schedulable {
    
    global void execute(SchedulableContext sc) {
        
        // SOQL query to find Annual Emission Inventory records eligible for deletion and not locked
        String query = 'SELECT Id FROM AnnualEmssnInventory WHERE AEI_Data_Archival_Criteria_Check__c = true AND Exclude_from_Archival__c = false AND Status__c != \'Pending for Approval\' AND IsRecordLocked = false';
        if (Test.isRunningTest()) {
            query = 'SELECT Id FROM AnnualEmssnInventory WHERE AEI_Data_Archival_Criteria_Check__c = true AND Exclude_from_Archival__c = false AND Status__c != \'Pending for Approval\' AND IsRecordLocked = false LIMIT 10';
        }

        // Execute the batch job with the deletion logic
        Database.executeBatch(new NZCAnnualEmissionInventoryBatchDelete(query), 25);
    }
}