force-app/main/default/objects/Energy_Use_Data_Log__c/Energy_Use_Data_Log__c.object-meta.xml
<CustomObject>
    <description>HT: Created for NZC Implementation UC003_US05, created to store the energy use data logs.</description>
    <label>Energy Use Data Log</label>
    <nameField>
        <displayFormat>Log-{00000}</displayFormat>
        <label>Energy Use Data Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Energy Use Data Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Energy_Use_Data_Log__c/fields/Archival_Criteria_Check__c.field-meta.xml
<CustomField>
    <fullName>Archival_Criteria_Check__c</fullName>
    <defaultValue>false</defaultValue>
    <description>AK: Created this field to mark fields for archival on completion of 180 days</description>
    <label>Archival Criteria Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/User_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Type__c</fullName>
    <description>HA: Created for NZC Implementation, Purpose: This Field indicates the type of user and his Responsibility.</description>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assurance Provider</fullName>
            </value>
            <value>
                <fullName>Business Admin</fullName>
            </value>
            <value>
                <fullName>Data Approver</fullName>
            </value>
            <value>
                <fullName>Data Modeller</fullName>
            </value>
            <value>
                <fullName>Data Processor</fullName>
            </value>
            <value>
                <fullName>Data Validator</fullName>
            </value>
            <value>
                <fullName>ESG Team</fullName>
            </value>
            <value>
                <fullName>Real Estate Team</fullName>
            </value>
            <value>
                <fullName>Suppliers</fullName>
            </value>
            <value>
                <fullName>System Admin</fullName>
            </value>
            <value>
                <fullName>Scope 3 CF Approver</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EnergyUseLogSchedulableTest.cls
@isTest
public class EnergyUseLogSchedulableTest {

    @testSetup
    static void createTestData(){
        List<Profile> profileDP = [SELECT Id FROM Profile WHERE name='Cog Net Zero Cloud Profile' LIMIT 1];
        User dpUser = new User(
            UserName = 'dataprocessor@cognizant.com.nzc99',
            FirstName = 'Test',
            LastName = 'Data Processor User',
            Alias = 'testDP',
            email = 'test@dpuser.com',
            ProfileId = profileDP[0].Id,
            EmailEncodingKey = 'UTF-8',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            User_Type__c = 'Data Processor',
            LanguageLocaleKey = 'en_US'
        );
        insert dpUser;
    }

    public static String CRON_EXP = '0 0 0 ? 1/3 * *';
	@isTest
    static void executeTest(){
        User u = [select Id from User where UserName='dataprocessor@cognizant.com.nzc99' limit 1];
        CronTrigger ct =  new CronTrigger();
        Test.startTest();
        System.runAs(u){
            Energy_Use_Data_Log__c el = new Energy_Use_Data_Log__c();
            el.Archival_Criteria_Check__c = true;
            insert el;
            String jobId = System.schedule('Test my class',
                        CRON_EXP, 
                        new EnergyUseLogSchedulable());
            ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
            String el1 = 'SELECT Id, Archival_Criteria_Check__c FROM Energy_Use_Data_Log__c WHERE Archival_Criteria_Check__c=true';
            EnergyUseLogBatchable batch = new EnergyUseLogBatchable(el1);
            DataBase.executeBatch(batch);

        }
        Test.stopTest();
        System.assertEquals(CRON_EXP, ct.CronExpression,'Test passed');
        
    }
}